### ISSUE TITLE
Issue generating in VS2022

### ISSUE THREAD

**Issue by mattwhitfield** [mattwhitfield/unittestgenerator#1]
When generating in VS2022 ->

Exception raised
System.MissingMethodException: Method not found: 'EnvDTE.Solution EnvDTE._DTE.get_Solution()'.

   at Unitverse.Helper.ProjectItemModel.get_TargetProject()

   at Unitverse.Commands.GenerateTestForSymbolCommand.<>c__DisplayClass13_0.<Execute>b__0() in D:\a\unittestgenerator\unittestgenerator\src\Unitverse\Commands\GenerateTestForSymbolCommand.cs:line 214

   at Unitverse.Helper.Attempt.Action(Action action, IUnitTestGeneratorPackage package) in D:\a\unittestgenerator\unittestgenerator\src\Unitverse\Helper\Attempt.cs:line 21

See https://developercommunity.visualstudio.com/t/dte-events-not-working-in-vs2022/1455126 
Also see https://cezarypiatek.github.io/post/migrate-vsix-to-vs2022/

**Comment by mattwhitfield** [comment]
This is resolved by version 0.73.0.0 - although means that the extension is now split into separate 2019 and 2022 extensions
